fix: integration build for docker-kafka 3 & 4

diff --git a/.github/workflows/integration-kafka-build.yml b/.github/workflows/integration-kafka-build.yml
--- a/.github/workflows/integration-kafka-build.yml
+++ b/.github/workflows/integration-kafka-build.yml
@@ -18,34 +18,11 @@ env:
   KAFKA_DISTRO_URL: ${{ github.event.client_payload.kafka-distro-url }}
   KAFKA_VERSION: ${{ github.event.client_payload.kafka-version }}
   REPLACE_SYMBOL: ${{ github.event.client_payload.replace-symbol }}
+  DOCKER_CONFIG_FILE: ".github/dev-build-config.cfg"
 
 jobs:
-  prepare-inputs:
-    runs-on: ubuntu-latest
-    outputs:
-      build_args: ${{ steps.set-vars.outputs.build_args }}
-    steps:
-      - name: Set Variables
-        if: github.event_name == 'repository_dispatch' && github.event.action == 'kafka-patched-build'
-        id: set-vars
-        run: |
-          kafka_distro_tgz="${KAFKA_DISTRO_URL##*/}"
-          echo 'build_args<<EOF' >> $GITHUB_OUTPUT
-          echo "KAFKA_DISTRO_URL=${KAFKA_DISTRO_URL}" >> $GITHUB_OUTPUT
-          echo "DISTRO_NAME=${kafka_distro_tgz%.*}" >> $GITHUB_OUTPUT
-          echo "KAFKA_VERSION=${KAFKA_VERSION}" >> $GITHUB_OUTPUT
-          echo 'EOF' >> $GITHUB_OUTPUT
-
-      - name: Debug
-        run: |
-          echo "build_args: ${{ steps.set-vars.outputs.build_args }}"
-      - name: Show payload
-        run: |
-          echo "${{ toJson(github.event.client_payload) }}"
-
   prepare:
     name: "Prepare Images and Metadata"
-    needs: [prepare-inputs]
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -53,7 +30,11 @@ jobs:
       components: ${{ steps.load.outputs.components }}
       platforms: ${{ steps.load.outputs.platforms }}
       tags: "${{ steps.meta.outputs.result }}"
+      kafka_major_version: ${{ steps.set-kafka-major-version.outputs.major }}
     steps:
+      - name: Show payload
+        run: |
+          echo "${{ toJson(github.event.client_payload) }}"
       - name: Checkout code
         uses: actions/checkout@v5
         with:
@@ -68,6 +49,7 @@ jobs:
           else
             git checkout -b ${INTEGRATION_BUILD_BRANCH} origin/${TARGET_REF}
           fi
+          git pull
 
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
@@ -76,12 +58,19 @@ jobs:
 
           git add .
           git commit -m "[IBuild] Updated ${INTEGRATION_BUILD_BRANCH} by ${TARGET_REF} to build qubership-kafka images with patched kafka from ${KAFKA_DISTRO_URL}"
-          git push origin "${INTEGRATION_BUILD_BRANCH}"
+          git push -f -u origin "${INTEGRATION_BUILD_BRANCH}"
 
       - id: load
         run: |
-          echo "components=$(jq -c '.components' .github/dev-build-config.cfg)" >> "$GITHUB_OUTPUT"
-          echo "platforms=$(jq -c '.platforms' .github/dev-build-config.cfg)" >> "$GITHUB_OUTPUT"
+          if [ -f ${DOCKER_CONFIG_FILE} ];then
+            echo "components=$(jq -c '.components' ${DOCKER_CONFIG_FILE})" >> "$GITHUB_OUTPUT"
+            echo "platforms=$(jq -c '.platforms' ${DOCKER_CONFIG_FILE})" >> "$GITHUB_OUTPUT"
+            echo "Components: $(jq '.components' ${DOCKER_CONFIG_FILE})"
+            echo "Platforms: $(jq '.platforms' ${DOCKER_CONFIG_FILE})"
+          else
+            echo "Configuration file ${DOCKER_CONFIG_FILE} not found."
+            exit 1
+          fi
 
       - name: Create tags for images
         uses: netcracker/qubership-workflow-hub/actions/metadata-action@v2.0.5
@@ -93,9 +82,16 @@ jobs:
           extra-tags: ${{ github.event.client_payload.tag }}
           replace-symbol: ${{ env.REPLACE_SYMBOL }}
 
+      - name: Set Kafka Major Version
+        id: set-kafka-major-version
+        uses: netcracker/qubership-workflow-hub/actions/metadata-action@v2.0.5
+        with:
+          ref: ${{ env.KAFKA_VERSION }}
+          default-template: "{{ref-name}}"
+
   build:
     name: ${{ matrix.component.name }}
-    needs: [prepare-inputs, prepare]
+    needs: [prepare]
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -105,6 +101,21 @@ jobs:
       matrix:
         component: ${{ fromJson(needs.prepare.outputs.components) }}
     steps:
+      - name: Set Variables
+        env:
+          DOCKER_KAFKA_VERSIONED_NAME: "qubership-docker-kafka-${{ needs.prepare.outputs.kafka_major_version }}"
+        if: github.event_name == 'repository_dispatch' && github.event.action == 'kafka-patched-build' && matrix.component.name == env.DOCKER_KAFKA_VERSIONED_NAME
+        id: set-vars
+        run: |
+          kafka_distro_tgz="${KAFKA_DISTRO_URL##*/}"
+          echo 'build_args<<EOF' >> $GITHUB_OUTPUT
+          echo "KAFKA_DISTRO_URL=${KAFKA_DISTRO_URL}" >> $GITHUB_OUTPUT
+          echo "DISTRO_NAME=${kafka_distro_tgz%.*}" >> $GITHUB_OUTPUT
+          echo "KAFKA_VERSION=${KAFKA_VERSION}" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
+          echo "build_args:"
+          cat $GITHUB_OUTPUT
+
       - name: Docker
         uses: netcracker/qubership-workflow-hub/actions/docker-action@v2.0.5
         with:
@@ -113,7 +124,7 @@ jobs:
           component: ${{ toJson(matrix.component) }}
           platforms: ${{ needs.prepare.outputs.platforms }}
           tags: ${{ needs.prepare.outputs.tags }}
-          build-args: ${{ needs.prepare-inputs.outputs.build_args }}
+          build-args: ${{ steps.set-vars.outputs.build_args }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -128,4 +139,3 @@ jobs:
     secrets:
       AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
       AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
-
